server: https://chat-service.ice.exchange
token_ethereum_service_url: https://ethereum.development.service.toshi.org
token_id_service_url: https://ice-id-service.herokuapp.com
redis:
    envKey: REDIS_URL
    timeout: 2000
storage:
  envKey: DATABASE_URL
  sslmode: require